const ActionType = {
	TOKEN: {
		FETCH_SUCCESS: 'FETCH_TOKEN_SUCCESS',
	},
	USER: {
		LOGIN: {
			FETCH: 'FETCH_USER_LOGIN',
		}
	},
	PLATE: {
		FETCH: 'FETCH_PLATE',
		FETCH_SUCCESS: 'FETCH_PLATE_SUCCESS',
		LIKE: 'LIKE_PLATE'
	},
	LOADING: {
		INCREMENT: 'INCREMENT',
		DECREMENT: 'DECREMENT',
	},
	MESSENGER: {
		SHOW: 'SHOW_MESSENGER',
		HIDE: 'HIDE_MESSENGER',
	}
};

export default ActionType;