const ActionType = {
	TOKEN: {
		FETCH_SUCCESS: 'FETCH_TOKEN_SUCCESS',
	},
	USER: {
		REGISTER: {
			FETCH: 'FETCH_USER_REGISTER',
		},
		LOGIN: {
			FETCH: 'FETCH_USER_LOGIN',
		},
		LOGOUT: {
			FETCH_SUCCESS: 'FETCH_USER_LOGOUT_SUCCESS',
		},
		PROFILE: {
			FETCH: 'FETCH_USER_PROFILE',
			FETCH_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
		},
	},
	LOADING: {
		INCREMENT: 'INCREMENT',
		DECREMENT: 'DECREMENT',
	},
	LOGIN_HISTORY: {
		SET: 'SET_HISTORY',
		GET: 'GET_HISTORY',
	},
	ERROR: 'ERROR',
};

export default ActionType;